name: lexicon
description: "A pure Dart package for background character dictionaries and grammar rules."
version: 0.0.1
homepage: https://github.com/SelinaErnst/lexicon
repository: https://github.com/SelinaErnst/lexicon
issue_tracker: https://github.com/SelinaErnst/lexicon/issues
license: MIT

environment:
  sdk: ^3.12.2

dependencies:
  meta: ^1.10.0 
  logging: ^1.2.0
  collection: ^1.18.0
  path: ^1.9.0
  
dev_dependencies:
  test: ^1.24.0    
  lints: ^3.0.0 
